micronaut:
  application:
    name: multidatasource
datasources:
  default:
    url: 'jdbc:mysql://localhost:3306/micronaut_test'
    username: root
    password: root
    default-read-only: false
    pool-name: 'read-write'

  readonly:
    url: 'jdbc:mysql://localhost:3306/micronaut_test'
    username: root
    password: root
    default-read-only: true
    pool-name: 'read-only'

jpa:
  default:
    entity-scan:
      packages: 'com.lajospolya'
    properties:
      hibernate:
        provider: none
      hbm2ddl:
        auto: none
      show_sql: true

  readonly:
    entity-scan:
      packages: 'com.lajospolya'
    properties:
      hibernate:
        provider: none
      hbm2ddl:
        auto: none
      show_sql: true

netty:
  default:
    allocator:
      max-order: 3
